apiVersion: apps/v1                 # API version for Deployment resource
kind: Deployment                  # This resource is a Deployment, manages pods
metadata:
  name: http-deployment           # Name of the Deployment
spec:
  replicas: 1                     # Number of pod replicas to run
  selector:
    matchLabels:                  # Select pods with label "app: http"
      app: http
  template:                      # Template for the pod managed by this Deployment
    metadata:
      labels:
        app: http                # Label applied to pods created by this Deployment
    spec:
      containers:                # List of containers in the pod
      - name: nginx              # Container name
        image: nginx             # Container image to run (nginx official image)
        ports:
        - containerPort: 80     # Expose port 80 inside the container
---
apiVersion: v1                    # API version for Service resource
kind: Service                    # This resource is a Service, exposes pods
metadata:
  name: http-service             # Name of the Service
spec:
  selector:
    app: http                   # Select pods with label "app: http" to forward traffic to
  ports:
  - port: 80                   # Service port exposed to the cluster or outside
    targetPort: 80             # Forward traffic to port 80 on the selected pods
  type: NodePort               # Service type NodePort exposes it on each node’s IP at a static port
