apiVersion: v1
kind: Pod
metadata:
  name: samba
  labels:
    name: samba
spec:
  containers:
  - name: samba
    image: dperson/samba
    args: ["-s", "public;/mount;yes;no;no;all;none"]
    ports:
    - containerPort: 139
    - containerPort: 445
---
apiVersion: v1
kind: Service
metadata:
  name: samba-service
spec:
  type: NodePort
  selector:
    name: samba
  ports:
  - name: smb139
    port: 139
    targetPort: 139
    nodePort: 31390
  - name: smb445
    port: 445
    targetPort: 445
    nodePort: 31445
